model: meta-llama/Meta-Llama-3.1-70B-Instruct
tensor_parallel_size: 8
providers:
  - vllm
  - sglang
  - torchinferno
benchmarks:
  - few_shot
  - self_consistency
  - multi_turn
  - tree_of_thought
  - long_output
build_dir: ./builds
results_dir: ./results/v1
server_port: 8000
server_startup_timeout: 1800
